### ISSUE TITLE
More compact internal representation

### ISSUE THREAD

**Issue by hvr** [haskell-hvr/uuid#24]
Currently, `UUID` is represented as

```hs
data UUID  = UUID
         {-# UNPACK #-} !Word32
         {-# UNPACK #-} !Word32
         {-# UNPACK #-} !Word32
         {-# UNPACK #-} !Word32
```

However, this suboptimal for 64bit archs (where GHC currently stores this a 320-byte Heap object); would you accept a PR switching to the internal representation (which is represented by GHC as 192-byte Heap objects on 64bit archs, also Ord/Eq operations would be more efficient)

```hs
data UUID  = UUID
         {-# UNPACK #-} !Word64
         {-# UNPACK #-} !Word64
```

?

This could either be made unconditional, or CPP-conditional on whether `Int`/`Word` is 64bit or 32bit wide.

**Comment by axman6** [comment]
Looks like this has been merged into master but not released. I wondered if maybe before releasing this instead of just changing the representation, CPP could be used to add a backwards compatible pattern synonym on 64 bit platforms, and have a new constructor for the 64 bit version.

```haskell
pattern UUID (fromIntegral (w12 `unsafeShiftR` 32)) (fromIntegral w12) 
             (fromIntegral (w34 `unsafeShiftR` 32)) (fromIntegral w34) 
             <- UUID64 w12 w34
    where UUID w1 w2 w3 w4 = UUID64 (w32to64 w1 w2) (w32to64 w3 w4)
```

I know it's all in an internal module, but it avoids a change which might break people's code.
